module: CollectionViewSlantedLayout
author: Yassir Barchi
author_url: http://yassir.fr
github_url: https://github.com/yacir/CollectionViewSlantedLayout
root_url: https://yassir.dev/CollectionViewSlantedLayout/
swift_version: 5.1
theme: fullwidth
exclude: Sources/Internal/*,Sources/Extentions/*
readme: README.md
output: docs
xcodebuild_arguments: 
  - "-project" 
  - "CollectionViewSlantedLayout.xcodeproj" 
  - "-scheme"
  - "CollectionViewSlantedLayout"